server.port=8082

spring.kafka.bootstrap-servers=kafka:9092

# Serializers are required to convert your Java objects/strings into bytes for Kafka
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

